name: pull request check
env:
  AWS_REGION: us-east-1
  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}


on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package
      - name: Build Deployment Artifact
        run: |
          pwd
          zip -r -j lambda_function_payload.zip ./target/handler-1.0-SNAPSHOT.jar
          pwd
          ls -al
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.aws-access-key-id}}
          aws-secret-access-key: ${{ env.aws-secret-access-key}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload Artifact to S3
        run: |
          pwd
          aws s3 cp ./target/handler-1.0-SNAPSHOT.jar s3://codedeploy.lambda.prod.suheel.me --region us-east-1
      - name: Make Lambda function update call
        run: |
          aws lambda update-function-code --region us-east-1 \
                                              --function-name csye6225 \
                                              --s3-bucket codedeploy.lambda.prod.suheel.me \
                                              --s3-key handler-1.0-SNAPSHOT.jar > lambda.txt
