name: pull request check
env:
  AWS_REGION: us-east-1
  aws-access-key-id: AKIAJ3FVA5JGS3A3H7AA
  aws-secret-access-key: 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

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn package
      - name: Build Deployment Artifact
        run: |
          pwd
          ls -al
          zip -r -j lambda.zip ./target/handler-1.0-SNAPSHOT.jar
          pwd
          ls -al
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.aws-access-key-id}}
          aws-secret-access-key: ${{ env.aws-secret-access-key}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload Artifact to S3
        run: |
          pwd
          aws s3 cp lambda.zip s3://codedeploy.lambda.prod.suheel.me/
          echo "Artifact uploaded to S3 successfully"
      - name: Make Lambda function update call
        run: |
          pwd
          aws lambda update-function-code --function-name csye6225 --region us-east-1 --zip-file fileb://lambda.zip
